model_dir: model_dir

data:
  train_features_file: tokenized/train.en
  train_labels_file: tokenized/train.es
  eval_features_file: tokenized/valid.en
  eval_labels_file: tokenized/valid.es
  source_vocabulary: tokenized/vocab.vocab
  target_vocabulary: tokenized/vocab.vocab

train:
  batch_size: 500
  keep_checkpoint_max: 5
  save_checkpoints_steps: 100

eval:
  external_evaluators: BLEU

infer:
  batch_size: 32
